// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//         {children}
//       </body>
//     </html>
//   );
// }


import ScrollToTop from '@/components/ScrollToTop/ScrollToTop'
import './globals.css'
import { Manrope } from 'next/font/google'
import FloatingWhatsApp from '@/components/FloatingWhatsApp/FloatingWhatsApp'

const manrope = Manrope({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  display: 'swap',
  variable: '--font-manrope'
})

export const metadata = {
  title: 'Ideas2Invest',
  description: 'Financial planning and advisory services',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={manrope.variable}>
      <body>
        <FloatingWhatsApp />
        <ScrollToTop />
        {children}
      </body>
    </html>
  )
}
