// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//         {children}
//       </body>
//     </html>
//   );
// }


import ScrollToTop from '@/components/ScrollToTop/ScrollToTop'
import './globals.css'
import { Manrope } from 'next/font/google'
import FloatingWhatsApp from '@/components/FloatingWhatsApp/FloatingWhatsApp'
import FloatingSidebar from '@/components/FloatingSidebar/FloatingSidebar'
import AiAssistant from '@/components/AiAssistant/AiAssistant'

const manrope = Manrope({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  display: 'swap',
  variable: '--font-manrope'
})

export const metadata = {
  title: 'Ideas2Invest - Your Goal, Our Objective',
  description: 'Empowering your financial future with expert planning and tailored investment strategies. At Ideas2Invest, we help you navigate your financial journey with personalized advice, innovative solutions, and a commitment to your success.',
  openGraph: {
    title: 'Ideas2Invest - Your Goal, Our Objective',
    description: 'Empowering your financial future with expert planning and tailored investment strategies. At Ideas2Invest, we help you navigate your financial journey with personalized advice, innovative solutions, and a commitment to your success.',
    images: [
      {
        url: '/assets/images/logo/logo.png',
        width: 800,
        height: 800,
        alt: 'Ideas2Invest Logo',
      },
    ],
    siteName: 'Ideas2Invest',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Ideas2Invest - Your Goal, Our Objective',
    description: 'Empowering your financial future with expert planning and tailored investment strategies. At Ideas2Invest, we help you navigate your financial journey with personalized advice, innovative solutions, and a commitment to your success.',
    image: '/assets/images/logo/logo.png',
  },
}

// export const metadata = {
//   title: 'Ideas2Invest - Your Goal, Our Objective',
//   description: 'Financial planning and advisory services',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={manrope.variable}>
      <body>
        <FloatingWhatsApp />
        <AiAssistant />
        <FloatingSidebar />
        {/* <ScrollToTop /> */}
        {children}
      </body>
    </html>
  )
}
