"use client";
import React, { useRef } from "react";
import styles from "./ComprehensiveCalculator.module.css";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";

export default function ReportExport({ results, reportRef, userInfo, isLoggedIn }) {

  const exportPDF = async () => {
    if (!isLoggedIn) {
      alert("Please log in to download your report.");
      return;
    }

    if (!results || !results.goals?.length)
      return alert("Please calculate results first.");

    const pdf = new jsPDF("p", "pt", "a4");
    const pageWidth = pdf.internal.pageSize.getWidth();
    let y = 40;

    // ✅ Add Branding Header
    pdf.addImage("/assets/images/logo/logo.png", "PNG", 40, 20, 120, 55);
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(22);
    pdf.text("Comprehensive Financial Report", 180, 55);

    y += 80;

    // ✅ Client Details Section
    pdf.setFontSize(12);
    pdf.setFont("helvetica", "normal");
    pdf.text(`Client Name: ${userInfo.name || "-"}`, 40, y);
    y += 18;
    pdf.text(`Prepared On: ${new Date().toLocaleDateString()}`, 40, y);
    y += 30;

    // ✅ Summary Cards Section
    const totalFuture = results.goals.reduce((a, b) => a + b.futureValue, 0);
    const totalSip = results.goals.reduce((a, b) => a + (b.sip || 0), 0);
    const totalLump = results.goals.reduce((a, b) => a + (b.lumpsum || 0), 0);

    pdf.setFontSize(14);
    pdf.setFont("helvetica", "bold");
    pdf.text("Investment Summary", 40, y);
    y += 18;

    pdf.setFont("helvetica", "normal");
    pdf.text(`Total Future Corpus Required: Rs. ${totalFuture.toLocaleString("en-IN", { maximumFractionDigits: 0 })}`, 40, y);
    pdf.text(`Total Monthly SIP Required: Rs. ${totalSip.toLocaleString("en-IN", { maximumFractionDigits: 0 })}`, 40, y + 16);
    pdf.text(`Total Lump-Sum Required: Rs. ${totalLump.toLocaleString("en-IN", { maximumFractionDigits: 0 })}`, 40, y + 32);

    // pdf.text(`Total Future Corpus Required: ₹${totalFuture.toLocaleString("en-IN", { maximumFractionDigits: 0 })}`, 40, y);
    // y += 16;
    // pdf.text(`Total Monthly SIP Required: ₹${totalSip.toLocaleString("en-IN", { maximumFractionDigits: 0 })}`, 40, y);
    // y += 16;
    // pdf.text(`Total Lump-Sum Required: ₹${totalLump.toLocaleString("en-IN", { maximumFractionDigits: 0 })}`, 40, y);
    // y += 30;

    // ✅ New Page for Detailed Goals
    y = 240;
    pdf.setFontSize(16);
    pdf.setFont("helvetica", "bold");
    pdf.text("Goal Breakdown", 40, y);
    y += 25;

    pdf.setFontSize(11);
    results.goals.forEach((g, index) => {
      if (y > 750) { pdf.addPage(); y = 40; }

      pdf.setFont("helvetica", "bold");
      pdf.text(`${index + 1}. ${g.name} (${g.type})`, 40, y);
      y += 14;

      pdf.setFont("helvetica", "normal");
      pdf.text(`Future Value: Rs. ${g.futureValue.toLocaleString("en-IN", { maximumFractionDigits: 0 })}`, 40, y);
      y += 14;
      pdf.text(`Monthly SIP: Rs. ${(g.sip || 0).toLocaleString("en-IN", { maximumFractionDigits: 0 })}`, 40, y);
      y += 14;
      pdf.text(`Lump Sum: Rs. ${(g.lumpsum || 0).toLocaleString("en-IN", { maximumFractionDigits: 0 })}`, 40, y);
      y += 22;
    });

    // ✅ Insert Charts (from on-page DOM — ensure charts exist)
    pdf.addPage();
    const chartCanvas = await html2canvas(document.getElementById("chart-section"), { scale: 2 });
    const chartImg = chartCanvas.toDataURL("image/png");
    const chartWidth = pageWidth - 80;
    const chartHeight = (chartCanvas.height * chartWidth) / chartCanvas.width;

    pdf.addImage(chartImg, "PNG", 40, y - 560, chartWidth, chartHeight);
    y += chartHeight + 30;

    // ✅ Footer Branding
    pdf.setFontSize(10);
    pdf.text("Report generated by Ideas2Invest", 40, 820);

    pdf.save("Ideas2Invest-Comprehensive-Report.pdf");
  };

  const sendWhatsApp = () => {
    if (!results) return alert("Calculate first.");
    const name = userInfo.name ? `for ${userInfo.name}` : "";
    let message = `Ideas2Invest - Financial Report ${name}%0A%0A`;
    results.goals.forEach(g => {
      message += `${g.name}: ₹${g.futureValue.toLocaleString("en-IN", { maximumFractionDigits: 0 })} (FV), SIP: ₹${(g.sip || 0).toLocaleString("en-IN", { maximumFractionDigits: 0 })}%0A`;
    });
    window.open(`https://wa.me/?text=${encodeURIComponent(decodeURIComponent(message))}`);
  };

  return (
    <div className={styles.card}>
      <h3>Export & Share</h3>
      <div className={styles.exportWrapper}>
        <button
          className={styles.primaryBtn}
          onClick={exportPDF}
          disabled={!isLoggedIn} // 👈 disables if not logged in
          title={!isLoggedIn ? "Please log in to download your report" : ""}
          style={!isLoggedIn ? { opacity: 0.6, cursor: "not-allowed" } : {}}
        >
          Download Report PDF
        </button>
        <button className={styles.secondaryBtn} onClick={sendWhatsApp}>
          Share via WhatsApp
        </button>
        {!isLoggedIn && (
          <p style={{ color: "#d00", marginTop: "8px", fontSize: "0.9rem" }}>
            🔒 Please log in to download your personalized report.
          </p>
        )}
      </div>
    </div>
  );
}


// "use client";
// import React, { useRef } from "react";
// import styles from "./ComprehensiveCalculator.module.css";
// import jsPDF from "jspdf";
// import html2canvas from "html2canvas";

// export default function ReportExport({ results, reportRef, userInfo }) {
//   const tempRef = useRef();

//   const exportPDF = async () => {
//     if (!results) return alert("No results to export. Calculate first.");
//     // create a printable DOM snapshot
//     const ele = tempRef.current;
//     // build snapshot content
//     ele.innerHTML = `
//       <div style="font-family: Arial, sans-serif; padding: 16px;">
//         <h2>Ideas2Invest — Comprehensive Report</h2>
//         <div><strong>Client:</strong> ${userInfo.name || "—"}</div>
//         <div style="margin-top:12px;">
//           ${results.goals.map(g => `<div style="margin-bottom:8px;">
//             <strong>${g.name}</strong> (${g.type}) — Future: ₹${g.futureValue.toLocaleString("en-IN", { maximumFractionDigits: 0 })}, SIP: ₹${(g.sip||0).toLocaleString("en-IN", { maximumFractionDigits: 0 })}, Lump-sum: ₹${(g.allocatedLumpsum||g.lumpsum||0).toLocaleString("en-IN", { maximumFractionDigits: 0 })}
//           </div>`).join("")}
//         </div>
//       </div>
//     `;
//     // render
//     ele.style.display = "block";
//     const canvas = await html2canvas(ele, { scale: 2 });
//     ele.style.display = "none";
//     const img = canvas.toDataURL("image/png");
//     console.log(img.slice(0, 50));
//     const pdf = new jsPDF("p", "pt", "a4");
//     const pdfW = pdf.internal.pageSize.getWidth();
//     const pdfH = (canvas.height * pdfW) / canvas.width;
//     pdf.addImage(img, "PNG", 0, 0, pdfW, pdfH);
//     pdf.save("Ideas2Invest-Comprehensive-Report.pdf");
//   };

//   const sendWhatsApp = () => {
//     if (!results) return alert("Calculate first.");
//     let msg = `Ideas2Invest - Financial Report for ${userInfo.name || ""}%0A%0A`;
//     results.goals.forEach((g) => {
//       msg += `${g.name} (${g.type}): Future ₹${g.futureValue.toLocaleString("en-IN", { maximumFractionDigits: 0 })}, SIP ₹${(g.sip||0).toLocaleString("en-IN", { maximumFractionDigits: 0 })}, Lump-sum ₹${(g.allocatedLumpsum||g.lumpsum||0).toLocaleString("en-IN", { maximumFractionDigits: 0 })}%0A`;
//     });
//     const url = `https://wa.me/?text=${encodeURIComponent(decodeURIComponent(msg))}`;
//     window.open(url, "_blank");
//   };

//   return (
//     <div className={styles.card}>
//       <h3>Export & Share</h3>
//       <div style={{ display: "flex", gap: 8 }}>
//         <button className={styles.primaryBtn} onClick={exportPDF}>Download PDF</button>
//         <button className={styles.secondaryBtn} onClick={sendWhatsApp}>Share on WhatsApp</button>
//       </div>
//       <div ref={tempRef} style={{ display: "none" }} />
//     </div>
//   );
// }
